// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqfbxjokwqhasuwgwoep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxZmJ4am9rd3FoYXN1d2d3b2VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwNTA3ODEsImV4cCI6MjA1MDYyNjc4MX0.BPG7r6E0BKu2lxHM99kLO2uvAWC5WvSavatYom99TwA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);